mergeSampleDict = {
        "TT_pow":       ["TT_pow",],
        "WJets":        [
                            "WJetsToLNu_LO",
                            "WJetsToLNu_HT70to100",
                            "WJetsToLNu_HT100to200",
                            "WJetsToLNu_HT200to400",
                            "WJetsToLNu_HT400to600",
                            "WJetsToLNu_HT600to800",
                            "WJetsToLNu_HT800to1200",
                            "WJetsToLNu_HT1200to2500",
                            "WJetsToLNu_HT2500toInf",
                        ],
        "DYJets":       [
                            "DYJetsToLL_M10to50_LO",
                            "DYJetsToLL_M50_LO",
                            "DYJetsToLL_M5to50_HT100to200",
                            "DYJetsToLL_M5to50_HT200to400",
                            "DYJetsToLL_M5to50_HT400to600",
                            "DYJetsToLL_M5to50_HT600toInf",
                            "DYJetsToLL_M50_HT70to100",
                            "DYJetsToLL_M50_HT100to200",
                            "DYJetsToLL_M50_HT200to400",
                            "DYJetsToLL_M50_HT400to600",
                            "DYJetsToLL_M50_HT600to800",
                            "DYJetsToLL_M50_HT800to1200",
                            "DYJetsToLL_M50_HT1200to2500",
                            "DYJetsToLL_M50_HT2500toinf",
                        ],
        "WZ":           ["WZTo3LNu"],
        "WW":           ["WWTo2L2Nu",],
        "ttVorH":       ["TTHnobb_pow","TTZToLLNuNu","TTZToLLNuNu_m1to10"],
        "ttW":          ["TTWToLNu"],
        "gamma+X":      ["WGToLNuG","TGJets","TTGJets","ZGTo2LG",],
        "Triboson":     ["WWW","WWZ","WZZ","ZZZ"],
        "SingleTop":    ["tWll",],
        "Minor":        [
                            "VHToNonbb",
                            "WWDoubleTo2L",
                            "WpWpJJ",
                            "ZZTo4L",
                            "TTTT",
                            "GGHZZ4L",
                            "TTHnobb_pow",
                        ],
        "QCD":          [
                            "QCD_HT100to200",
                            "QCD_HT200to300",
                            "QCD_HT300to500",
                            "QCD_HT500to700",
                            "QCD_HT700to1000",
                            "QCD_HT1500to2000",
                            "QCD_HT2000toInf",
                        ],
        }
