mergeSampleDict = {
        "TT_pow":       ["TT_pow",],
        "WJets":        ["WJetsToLNu_LO",],
        "DYJets":       ["DYJetsToLL_M10to50_LO","DYJetsToLL_M50_LO",],
        "WZ":           ["WZTo3LNu"],
        "WW":           ["WWTo2L2Nu",],
        "ttVorH":       ["TTHnobb_pow","TTZToLLNuNu","TTZToLLNuNu_m1to10"],
        "ttW":          ["TTWToLNu"],
        "gamma+X":      ["WGToLNuG","TGJets","TTGJets","ZGTo2LG","WGToLNuG",],
        "Triboson":     ["WWW","WWZ","WZZ","ZZZ"],
        "SingleTop":    ["tWll",],
        "Minor":        [
                            "VHToNonbb",
                            "WWDoubleTo2L",
                            "WpWpJJ",
                            "ZZTo4L",
                            "TTTT",
                            "GGHZZ4L",
                            "TTHnobb_pow",
                        ],
        "QCD":          [
                            "QCD_HT100to200",
                            "QCD_HT200to300",
                            "QCD_HT300to500",
                            "QCD_HT500to700",
                            "QCD_HT700to1000",
                            "QCD_HT1500to2000",
                            "QCD_HT2000toInf",
                        ],
        }
