mergeSampleDict = {
        #"ggH":  ["ggH"],
        #"VBF":  ["VBF"],
        #"WH":   ["WHPlus","WHminus",],
        #"ZH":   ["ZH",],
        "Higgs":    ["ggH","VBF","WHPlus","WHMinus","ZH",],
        #"qqZZ": ["qqZZTo4L",],
        #"ggZZ": [
        #    "ggZZTo2e2mu",
        #    "ggZZTo2e2tau",
        #    "ggZZTo2mu2tau",
        #    "ggZZTo4e",
        #    "ggZZTo4mu",
        #    "ggZZTo4tau",
        #    ],
        "ZZ": [
            "qqZZTo4L",
            "ggZZTo2e2mu",
            "ggZZTo2e2tau",
            "ggZZTo2mu2tau",
            "ggZZTo4e",
            "ggZZTo4mu",
            "ggZZTo4tau",
            ],
        "ZPlusX": ["ZPlusX"],
        }
